# Generated by Django 2.2.28 on 2022-09-10 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Profiles', '0002_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='Category',
            field=models.CharField(choices=[('machine learning', 'Machine Learning'), ('data science & ai', 'Data Science & Ai'), ('cloud computing', 'Cloud Computing')], max_length=50),
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Project_Name', models.CharField(max_length=100)),
                ('Platform', models.CharField(max_length=50)),
                ('Technologies', models.CharField(max_length=50)),
                ('Description', models.TextField()),
                ('Category', models.CharField(choices=[('machine learning', 'Machine Learning'), ('data science ', 'Data Science '), ('web', 'Web'), ('android app', 'Android')], max_length=100)),
                ('Github_url', models.URLField(blank=True, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('User', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Profiles.Profile')),
            ],
        ),
    ]
